### ISSUE TITLE
Install instructions do NOT work

### ISSUE THREAD

**Issue by cyberjaguar** [ember-learn/super-rentals#138]
Today I just wanted to do some research about how cool ember octane is because I wanted to see some really good architectural brilliance and wanted to delight myself with glancing at admirable code, after spending some weeks in very dark areas of web dev I need that. 

I cloned the repo, did `yarn install` and `ember serve` and I get this:
```
user@bionic:~/tmp/ember/super-rentals -> ember serve
Required packages are missing, run `yarn install` from this directory to install them.

user@bionic:~/tmp/ember/super-rentals -> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ ember-cli-babel@npm:6.17.2 doesn't provide @babel/core@^7.0.0-beta.42 requested by babel-plugin-debug-macros@npm:0.2.0
➤ YN0002: │ ember-cli-typescript@npm:2.0.0 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-class-properties@npm:7.4.0
➤ YN0002: │ ember-cli-typescript@npm:2.0.0 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-transform-typescript@npm:7.4.0
➤ YN0002: │ ember-compatibility-helpers@npm:1.1.2 doesn't provide @babel/core@^7.0.0-beta.42 requested by babel-plugin-debug-macros@npm:0.2.0
➤ YN0000: └ Completed in 0.31s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.66s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1.89s
➤ YN0000: Done with warnings in 2.93s
user@bionic:~/tmp/ember/super-rentals -> ember serve
Required packages are missing, run `yarn install` from this directory to install them.
```
I did already a `yarn install` before which generated of course much more output, the fragments above show that I did try that again after that frustrating `ember serve`.

It just does not work on step 1. 
 
Now I am very hungry.

**Comment by chancancode** [comment]
Hi @cyberjaguar, do you know which branch you are on? You can tell by running `git branch` in the folder after you cloned the repository.

The code matching the current version of the tutorial lives in the `super-rentals-tutorial` branch, *not* the master branch. (I am sorry for the confusion, we are in the middle of moving things around.)

**Comment by chancancode** [comment]
@cyberjaguar #141 has been merged and now master matches the latest tutorial, and the instructions should work. Let me know if you are still running into issues!
