### ISSUE TITLE
where is the css file?

### ISSUE THREAD

**Issue by ainneo** [ember-learn/super-rentals#140]

**Comment by chancancode** [comment]
Hi @ainneo! If you are following the [current tutorial](https://guides.emberjs.com/release/tutorial/part-1/orientation/), the CSS file is linked from the text in the "Orientation" chapter:

> Fortunately, our designer sent us some CSS to use, so we can [download the stylesheet file](https://guides.emberjs.com/downloads/style.css) and copy it into app/styles/app.css. This file has all the styles we need for building the rest of the app.

#141 will also add that file to this repo. In the meantime, you can reference [this branch](https://github.com/ember-learn/super-rentals/tree/super-rentals-tutorial-output) if you want to see the output of the current tutorial.

**Comment by chancancode** [comment]
#141 is merged so this should be fixed now!
