### ISSUE TITLE
search on demo app does not work

### ISSUE THREAD

**Issue by growandwin** [ember-learn/super-rentals#155]
Hi, I visited https://ember-super-rentals.netlify.app/ and tried search - no matter what I write, the result list becomes empty

**Comment by ijlee2** [comment]
Hi, @growandwin. Can you tell us more about what you typed in for search?

There are 3 rental properties and I was able to filter them by typing a letter. I did notice that filtering is case-sensitive. Perhaps that could be why?

**Comment by rajasegar** [comment]
The search is case-sensitive and from the first character of the names, so you should try with something like `Grand`, `Urban`, `Down`

**Comment by ijlee2** [comment]
Closing this issue since the search was working as intended.
