### ISSUE TITLE
Wide property CSS is conflicting and doesn't work as intended

### ISSUE THREAD

**Issue by ruppalsingh** [ember-learn/super-rentals#32]
```
.listing .wide {
  max-width: 100%;
  position: relative;
  z-index: 999;
}

.listing .wide img {
  height: initial;
  width: 100%;
}

.listing .wide small {
  display: none;
}

.listing a.image {
  max-width: 150px;
  display: block;
}
```

Since `max-width` is set to `150px`, and the default is set to `136px`, a toggle on the image doesn't fill the container width, and only expands to 150px. Hence, the image shown on the [Ember Tutorial](https://guides.emberjs.com/v2.6.0/tutorial/simple-component/) page is not the actual end result when going through the tutorial.

This is also in addition to the 'View Larger' not being centered as shown in the image. I would submit a pull request, but I just wanted to be sure I have correctly diagnosed the issue and that it's not just me with the problem. :)

**Attachments with the default behaviour:**

![issue-1](https://cloud.githubusercontent.com/assets/3974019/16896050/8cc7ea74-4ba5-11e6-8a17-60611da4718e.png)
![issue-2](https://cloud.githubusercontent.com/assets/3974019/16896051/8cceb4b2-4ba5-11e6-92a6-57c30253f5c7.png)

**Comment by toddjordan** [comment]
@ruppalsingh A fix was submitted to the css addon and is now at 0.0.5. please re-run `ember install ember-cli-tutorial-style` and see if that fixes it for you .  Thanks for reporting.

https://github.com/toddjordan/ember-cli-tutorial-style/issues/2

**Comment by toddjordan** [comment]
Should be fixed now.  Let me know if its not...
