### ISSUE TITLE
Ember-cli generate test problem.

### ISSUE THREAD

**Issue by parobit** [ember-learn/super-rentals#50]
When i try `ember g acceptance-test list-rentals` . It just return `installing acceptance-test` without file created.
```
ember-cli: 2.11.1
node: 6.9.4
npm: 3.10.10
os: win32 x64
```

**Comment by locks** [comment]
Thanks for reporting @parobit. This is already being addressed at the [ember.js](https://github.com/emberjs/ember.js/pull/14937) level, so please follow that PR if you want to follow along :)
