### ISSUE TITLE
Fail on bower install

### ISSUE THREAD

**Issue by batisteo** [ember-learn/super-rentals#53]
$ `ember --version`
```bash
ember-cli: 2.12.0
node: 7.7.3
os: linux x64
```

$ `git clone https://github.com/ember-learn/super-rentals.git`

$ `npm install`
```
Installing stuff…
```

$ `bower install`
```javascript
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/usr/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

$ `ember --version`
```bash
Missing bower packages: 
Package: pretender
  * Specified: ~0.10.1
  * Installed: (not installed)

Package: Faker
  * Specified: ~3.0.0
  * Installed: (not installed)

Run `bower install` to install missing dependencies.

```

**Comment by toddjordan** [comment]
Hmm. I just ran this Saturday night, and again just now.  I might not have CLI 2.12 though.  Trying to reproduce with that.

make sure you try a "nombom", which is
npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install

**Comment by toddjordan** [comment]
2.12.0 works for me.  

If the command I sent you doesn't work (clearing cache, rm directories, install)
Also tell me what your node/npm/bower versions are.  I'm at 6.9.4/3.10.10/1.6.5
sometimes an old node js version can mess things up.

**Comment by acorncom** [comment]
@batisteo Are you still seeing issues here?  If not, we'll go ahead and close this ...

**Comment by batisteo** [comment]
It’s all fine after upgrading everything!
