### ISSUE TITLE
Update Tutorial for "property-type"

### ISSUE THREAD

**Issue by smaloneyzenefits** [ember-learn/super-rentals#70]
Please update the online tutorial for "property-type" instead of propertyType otherwise there is a serialization error.

**Comment by vain6** [comment]
As a workaround, you can generate a serializer:

ember g serializer application

And then add these contents to the file:

import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
  keyForAttribute(key) {
    return key;
  }
});

**Comment by Raj-keviv** [comment]
@vain6  You are Correct i added these lines my project now working fine. But its nice if Tutorial is edited for this correction

**Comment by locks** [comment]
This seems to already be updated in master of both the tutorial and this!
