### ISSUE TITLE
demo heroku app is missing Google Maps API

### ISSUE THREAD

**Issue by iirving** [ember-learn/super-rentals#75]
When running the demo app (https://ember-learn-super-rentals.herokuapp.com/rentals) the google map is not working (looks broken)

from the developer console:

Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
_.rb @ js?v=3.22:35
util.js:216 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
uB.j @ util.js:216
util.js:216 Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
uB.j @ util.js:216

I was easily able to use the "Deploy to Heroku" function to successfully run the application, after generating a map api key and adding to the "Config Vars". 

I expect the demo version just needs a new key to be generated and added to the heroku dashboard for the app.

**Comment by sivakumar-kailasam** [comment]
Fixed with the latest `app.json` configuration. Should prompt for an api key on deploying now with the 'Deploy to Heroku' button
