### ISSUE TITLE
Filters aren't represented as query params

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/super-rentals#80]
Goto https://ember-learn-super-rentals.herokuapp.com/rentals enter 'San Franciso' as the location, you don't see it update a query param which is misleading for newbies. We should probably support it.

**Comment by toddjordan** [comment]
hmm.  There's no web standard that I know of that says that a UI searches need to be represented as a query params.  Its pretty common that RESTful API GET commands utilize query params to filter data returned from the server, which is I believe what we do, and is reflected in the console. 

![image](https://user-images.githubusercontent.com/3609063/35400532-a399e260-01bc-11e8-9f1c-74af7c368158.png)

I don't think its useful to represent query params in the browser window, unless we are explicitly explaining in the tutorial why we are doing it (which would be to create bookmark-able search results, and history of searches).  We probably would want to add a new page to the tutorial for it. Not sure that's in scope of what we want to do.  

If we decide that we should bring the concept of Ember query params to the tutorial, then its a good place to add them, but I think its something that the learn team should have a discussion about.  

@locks do you have an opinion?

**Comment by acorncom** [comment]
I think if we're aiming for super rentals to be our mid-tier tutorial it would make sense to introduce query params down the road. But until we've got our intro tier tutorial up and going, it could feel like we're burying people in a ton of details. So would be inclined to punt this down the road myself ...

**Comment by toddjordan** [comment]
Closing until we decide to add query params to the tutorial
