### ISSUE TITLE
Alternative to yarn install

### ISSUE THREAD

**Issue by ssabat** [ember-learn/super-rentals#88]
I tried to install yarn  way and it will not succeed in my Ubuntu 16.04 LTS setup which is as

4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu tells me to install cmdtest instead. I installed cmdtest. yarn gets installed and it will not recognize install parameter. I spent lot of time. I found package.json file in super rentals directory.  So, I used "npm install"  to install the sample app. It worked and I could bring up SuperRentals website at localhost:4200.

Just wanted to share my findings with folks who have issue installing yarn way.

Thanks,

Sunil Sabat

**Comment by locks** [comment]
According to https://github.com/yarnpkg/yarn/issues/3189, it seems like it was a problem with Aptitude's package registry.
Thanks for the heads up!
