### ISSUE TITLE
Missing / incomplete integration test

### ISSUE THREAD

**Issue by BeaverValley** [ember-learn/super-rentals#96]
Hi, I've been working through v3.0.0 of the tutorial. On the page [Creating a Handlebars Helper](https://guides.emberjs.com/v3.0.0/tutorial/hbs-helper/) I'm having trouble getting the integration tests to pass (see attached screen shot). 

When I look to the official repo to compare code, I can't find the corresponding file that would contain these integration tests:
\super-rentals\tests\integration\helpers\rental-property-type-test.js

![rental-property-type-test](https://user-images.githubusercontent.com/10797116/37420689-c2d231b8-278d-11e8-8a00-ba4693fa645c.jpg)

**Comment by toddjordan** [comment]
Thanks for reporting. I added the test but it works for me.  PR'ing it to this repo, and also updating the tutorial to use the new test apis.

**Comment by toddjordan** [comment]
fixed by #120
